# Generated by Django 3.0.8 on 2020-07-19 18:28

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import session.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booklet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booklet_type', models.CharField(choices=[(0, '10'), (1, '5'), (2, '4,3,3')], default=0, max_length=1)),
            ],
            managers=[
                ('booklets', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.CharField(max_length=45)),
                ('overall_mark', models.PositiveIntegerField()),
                ('booklet', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='session.Booklet')),
            ],
            managers=[
                ('pages', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.PositiveIntegerField()),
                ('timestamp', session.models.UnixTimestampField(null=True)),
                ('status', models.PositiveIntegerField()),
            ],
            managers=[
                ('sessions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marking_outcome', models.CharField(max_length=45)),
                ('correct_ans', models.CharField(max_length=45)),
                ('pred_regex', models.CharField(max_length=45)),
                ('images', models.TextField()),
                ('page', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='session.Page')),
            ],
            managers=[
                ('questions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='booklet',
            name='session',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booklet', to='session.Session'),
        ),
    ]
